server:
  port: 8080
  contextPath: /diceware

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# logging.level.com.cultureofcode.diceware.client.NumberServiceClient: DEBUG
